[workspace]
members = ["core", "xtask"]
resolver = "3"

[workspace.package]
edition = "2024"
rust-version = "1.85"
authors = ["Umberto Gotti <umberto.gotti@umbertogotti.dev>"]
license = "MIT"
repository = "https://github.com/umbgtt10/iceberg4rust"

[workspace.dependencies]
anyhow = "1.0.98"
cargo_metadata = "0.23.1"
clap = { version = "4.6.0", features = ["derive"] }
proc-macro2 = { version = "1.0", features = ["span-locations"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
syn = { version = "2.0.117", features = ["full", "visit"] }
walkdir = "2.5.0"
